### PR TITLE
Clearing out excess requirements

### PR DESCRIPTION
**Pull request by fearphage**
Reduced `install_requires` to the bare necessities needed to run the library. 

Just the bear necessities of life!

> It is not considered best practice to use ``install_requires`` to pin
dependencies to specific versions, or to specify sub-dependencies
(i.e. dependencies of your dependencies).  This is overly-restrictive, and
prevents the user from gaining the benefit of dependency upgrades.
>
> Lastly, it's important to understand that ``install_requires`` is a listing of
"Abstract" requirements, i.e just names and version restrictions that don't
determine where the dependencies will be fulfilled from (i.e. from what
index or source).  The where (i.e. how they are to be made "Concrete") is to
be determined at install time using :ref:`pip` options.

@ustudio/dev :eyes:

---
This change is [Reviewable](https://reviewable.io/reviews/ustudio/storage/31)

### CODE REVIEW

**Comment by spiralman** [comment]
*[circle.yml, line 5 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/31#-KOD1UYynYb5xfWGH9EQ:-KOD1UYzq6PrIjUNw_xm:392410327) ([raw file](https://github.com/ustudio/storage/blob/74ec7053ddcdd43480018f8823a93bd31f1b1212/circle.yml#L5)):*
> ```YAML
>     - nosetests tests
>   pre:
>     - pip install -e .
> ```

You should do this in the `dependencies` section (`post` would be closest to `pre` test, but I'm not sure it matters), so that Circle has a chance to cache any results (it saves off the cache between the `dependencies` and `test` sections).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31)*

**Comment by spiralman** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31)*

**Comment by fearphage** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[circle.yml, line 5 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/31#-KOD1UYynYb5xfWGH9EQ:-KOD73YqSiOCcAI-UwhG:-499146009) ([raw file](https://github.com/ustudio/storage/blob/74ec7053ddcdd43480018f8823a93bd31f1b1212/circle.yml#L5)):*
<details><summary><i>Previously, spiralman (Thomas Stephens) wrote…</i></summary>
> You should do this in the `dependencies` section (`post` would be closest to `pre` test, but I'm not sure it matters), so that Circle has a chance to cache any results (it saves off the cache between the `dependencies` and `test` sections).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31)*

**Comment by spiralman** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31)*

**Comment by spiralman** [comment]
*[setup.py, line 10 \[r2\]](https://reviewable.io:443/reviews/ustudio/storage/31#-KOD7p310zPjpOL7koeL:-KOD7p326d2LNEjIW2xW:-1883788301) ([raw file](https://github.com/ustudio/storage/blob/c01a97d8f5a6b68fbcfbbc66c9ff0df41ad0b405/setup.py#L10)):*
> ```Python
> 
> setup(name="object_storage",
>       version="0.7.1",
> ```

Oops, forgot about this; need to bump the version number.

I think we also call out the latest version number in the README file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31)*

**Comment by fearphage** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup.py, line 10 \[r2\]](https://reviewable.io:443/reviews/ustudio/storage/31#-KOD7p310zPjpOL7koeL:-KOF_UIyDHUiPxvkTyuR:71185568) ([raw file](https://github.com/ustudio/storage/blob/c01a97d8f5a6b68fbcfbbc66c9ff0df41ad0b405/setup.py#L10)):*
<details><summary><i>Previously, spiralman (Thomas Stephens) wrote…</i></summary>
> Oops, forgot about this; need to bump the version number.
> 
> I think we also call out the latest version number in the README file.
</details>
I generally do that on master before I create a release tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31)*

**Comment by spiralman** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/31#-:-KOGZLlzSAhRrFMcZZbg:1417088721)*

**Pull request merged**
