### PR TITLE
Implemented get_download_url for S3 storage

### PR DESCRIPTION
**Pull request by tantona**
@ustudio/dev

[Review on Reviewable](https://reviewable.io/reviews/ustudio/storage/20)

### CODE REVIEW

**Comment by spiralman** [comment]
<sup>**[storage/storage.py, line 465 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/20#-Jww3goaF1iqeh-IBL9j)** ([raw file](https://github.com/ustudio/storage/blob/d4c3a65d1e82447763c42f15871b218686bdff49/storage/storage.py#L465)):</sup>
Clients of this library will be using the interface provided by the `Storage` base class, so they won't be able to pass in this custom `http_method` parameter (unless they check the storage protocol before calling this function, but that would defeat the purpose of the library, which is to not care about storage protocols).

What is the purpose of the `http_method` parameter. Is it possible to just provide a fixed default value?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by spiralman** [comment]
<sup>**[tests/test_storage.py, line 1048 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/20#-Jww5jUpM0mfwxZFDMrw)** ([raw file](https://github.com/ustudio/storage/blob/d4c3a65d1e82447763c42f15871b218686bdff49/tests/test_storage.py#L1048)):</sup>
You should, ideally, have a test for overriding the default parameters (`expires_in` and `http_method`, although see above about `http_method`).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by spiralman** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by ckrough** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[storage/storage.py, line 428 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAcG4dxSY_nD_JB3u7)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/storage/storage.py#L428)):</sup>
[MINOR] You may want to look into connection pooling or connection re-use here since we call this a lot and there is probably a per-key connection limit in the AWS API

---

<sup>**[storage/storage.py, line 447 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAc8rc-tnnmqR3ETS9)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/storage/storage.py#L447)):</sup>
[MAJOR] Should this check the file MD5 upon completion to ensure that it's not corrupt? I would also verify that BOTO is handling retries and if not, implement some retry magic up in this mutha.

---

<sup>**[storage/storage.py, line 449 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAbWOCpHUG8AjyBgev)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/storage/storage.py#L449)):</sup>
[MINOR] What's the app behavior if a chunk is corrupt or the connection is broken before all chunks are received. You may want to check that the upstream consumer does the right thing here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by ckrough** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[tests/test_storage.py, line 976 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAfFhDN2Yb8ZP-I-kq)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/tests/test_storage.py#L976)):</sup>
[MAJOR] This code path would be more rugged if we tested failures (connect, 500's) using something like HTTPPretty to ensure that we can coast through network hiccups

---

<sup>**[tests/test_storage.py, line 1047 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAfnXehAEtzM9oni6I)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/tests/test_storage.py#L1047)):</sup>
[NOTE] Take a look at MOTO, the Mock Boto lib: https://github.com/spulec/moto

---

<sup>**[tests/test_storage.py, line 1048 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAgCeQ-5NyF9E5Eyoh)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/tests/test_storage.py#L1048)):</sup>
[NOTE] Can this test be omitted since it's functionality can be asserted in one of the higher level workflow tests?

---

<sup>**[tests/test_storage.py, line 1071 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAgSMeN1sUnd1iCv9D)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/tests/test_storage.py#L1071)):</sup>
[NOTE] Can this test be omitted since it's functionality can be asserted in one of the higher level workflow tests?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by ckrough** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by ckrough** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by aztlan2k** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[setup.py, line 9 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAgzK8fjQdCv8uvxjj)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/setup.py#L9)):</sup>
[MINOR] [DEFECT] don't forget to update the associated version in the `README.md`

---

<sup>**[storage/storage.py, line 428 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAcG4dxSY_nD_JB3u7)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/storage/storage.py#L428)):</sup>
every call to the storage library is independent, so we probably can't use connection pooling...   

---

<sup>**[storage/storage.py, line 469 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAincKjMS2gvEDTmU3)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/storage/storage.py#L469)):</sup>
[QUESTION] should we be removing a param (`key=None`) that the abstract class declares?    Shouldn't we just let it be even if we don't use it?  Not sure what the pythonic way of dealing with that is.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by spiralman** [comment]
<sup>**[storage/storage.py, line 447 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAc8rc-tnnmqR3ETS9)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/storage/storage.py#L447)):</sup>
Retry logic is implemented in the client code (API, TaskNode, tec), using the retry library provided by the storage library.

Retrying individual chunks is error prone, so we have found it best to just retry the whole request, which is why we leave it up to the client (they can also decide how many attempts is appropriate for their application, etc.).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by spiralman** [comment]
<sup>**[tests/test_storage.py, line 1048 \[r3\]](https://reviewable.io:443/reviews/ustudio/storage/20#-JxAgCeQ-5NyF9E5Eyoh)** ([raw file](https://github.com/ustudio/storage/blob/ef9283aa9d387f6e195c84412cc7ec6703dcb1ce/tests/test_storage.py#L1048)):</sup>
Im not sure what you mean by the higher level workflow tests? We don't have any standalone tests of `_connect`, so we repeat the connection/authentication assertion in each test.

We could also mock out `_connect`, assert that it was called, and then write a test for `_connect`, but that would be testing an internal function, which is also not a great pattern.

Alex asked me about this in person, and I suggested he do it this way, to maintain consistency with the rest of the tests, since either way has a downside.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Comment by ckrough** [comment]
Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/20)

**Pull request merged**
