### PR TITLE
Added load_from_directory and save_to_directory APIs

### PR DESCRIPTION
**Pull request by fearphage**
Added two new methods:

* load_from_directory
* save_to_directory

Note: These methods essentially make copies of folders either in the cloud or locally.

@ustudio/dev :eyes:

---
This change is [Reviewable](https://reviewable.io/reviews/ustudio/storage/28)

### CODE REVIEW

**Comment by spiralman** [comment]
*[README.md, line 62 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe6JvFAQeKoUyypvra:-KFe6JvGg37pCf9wXTuR:-516262540) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/README.md#L62)):*
MINOR: does this need a line break?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 259 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe7IWkcUHRW4F9p79K:-KFe7IWkcUHRW4F9p79L:-15016715) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L259)):*
Use `os.path.join`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 260 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe7RpcEDYBn3s-Dvv4:-KFe7RpcEDYBn3s-Dvv5:1859258418) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L260)):*
Given how you've split up the directory and file lists above, it's unnecessary to check the content_type here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 258 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe8M8xCBtJa3RW2DPX:-KFe8M8xCBtJa3RW2DPY:2093965452) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L258)):*
This is the same as `os.path.basename(directory.name)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 258 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe8M8xCBtJa3RW2DPX:-KFe8_MGVxNldWUGw_gT:1391050887) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L258)):*
NM, misread the code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 266 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe8gHxFGLbKNpxWpQM:-KFe8gHyz45RCu6W5ceh:-1650665383) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L266)):*
This, however, is the same as `os.path.basename(filename)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 292 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe9IN-fF7sFo9cRP2S:-KFe9IN-fF7sFo9cRP2T:-28478727) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L292)):*
MINOR: this isn't really the `relative_path`, it's more the `container_path`, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 595 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeC4DA5M6z1ZReI8UR:-KFeC4DA5M6z1ZReI8US:515809883) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L595)):*
This is just `os.path.basename(file_key)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
*[storage/storage.py, line 593 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeCpsV5fOYYRVvwUvL:-KFeCpsV5fOYYRVvwUvM:-343817630) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L593)):*
`file_key.replace(self._keyname, "", 1)` feels more like a higher level description of what you mean here; the current code reads like (slightly abbreviated) C code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
Reviewed 3 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by fearphage** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[storage/storage.py, line 259 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe7IWkcUHRW4F9p79K:-KFeYCeLidUPDuUVNk0h:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L259)):*
Done.

---

*[storage/storage.py, line 260 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe7RpcEDYBn3s-Dvv4:-KFeYBtAY1t6ELSDHnv3:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L260)):*
Done.

---

*[storage/storage.py, line 266 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe8gHxFGLbKNpxWpQM:-KFeYAhyojzD1sM9Lhyh:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L266)):*
Done.

---

*[storage/storage.py, line 292 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe9IN-fF7sFo9cRP2S:-KFeYTiN_7K07BcSu3JE:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L292)):*
Done.

---

*[storage/storage.py, line 593 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeCpsV5fOYYRVvwUvL:-KFeYzrCXdkgpBEkBT8s:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L593)):*
Done.

---

*[storage/storage.py, line 595 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeC4DA5M6z1ZReI8UR:-KFeYzMYT61ObaCts3-H:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/storage/storage.py#L595)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by fearphage** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 62 \[r9\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe6JvFAQeKoUyypvra:-KFeb9WZt74zU16cXF5t:-499146009) ([raw file](https://github.com/ustudio/storage/blob/5e47fada4236a6dfc03aa686c9eda5d96969f0c7/README.md#L62)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by aztlan2k** [comment]
Reviewed 1 of 3 files at r8.
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[storage/storage.py, line 86 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFQtc7I_ukVbxLjBoIw:-KFQtc7JM6QdxJ5un4wR:216561862) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L86)):*
add an example for use with a directory.

```
file:///some/path/to/a/directory?[download_url_base=<URL-ENCODED-URL>]
```

---

*[storage/storage.py, line 405 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeZamExWrWMr_gIB5b:-KFeWvkKeDynmHhA8IE7:1021793557) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L405)):*
i guess it's pretty much the same thing but you could have used `ftp_client.dir(directory_listing.append)`.  

kinda sucks there isn't a better method of getting the dirs/files.

---

*[storage/storage.py, line 408 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe_h8baB826SqmVlhe:-KFe_h8baB826SqmVlhf:696342864) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L408)):*
just curious, but should we considering filenames with spaces?  

---

*[tests/test_storage.py, line 15 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFQkVk0CRpp6ZcjM_rd:-KFQkVk113CUrQrSt5qv:-72455411) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/tests/test_storage.py#L15)):*
`...input_one, temp_input_two, nested_temp_directory/...`   (*add space*)  just so it's consistent.

but maybe something like this might look clearer?

```
# temp_directory/
#     temp_input_one
#     temp_input_two
#     nested_temp_directory/
#         nested_temp_input
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by aztlan2k** [comment]
Reviewed 1 of 3 files at r8, 1 of 1 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by aztlan2k** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[README.md, line 16 \[r11\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeckeYakQLaiPyOkY8:-KFeckeZcMw01BWMGbEu:979574366) ([raw file](https://github.com/ustudio/storage/blob/2d826d154a3c1dd5e2097f8c3c29679097aed8db/README.md#L16)):*
needs updating.   as well as `setup.py`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by spiralman** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by fearphage** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 16 \[r11\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeckeYakQLaiPyOkY8:-KFexpG417rV7CYZY7qX:-499146009) ([raw file](https://github.com/ustudio/storage/blob/2d826d154a3c1dd5e2097f8c3c29679097aed8db/README.md#L16)):*
Done.

---

*[storage/storage.py, line 86 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFQtc7I_ukVbxLjBoIw:-KFeyFGgFJP7repEDS3g:-499146009) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L86)):*
Done.

---

*[storage/storage.py, line 405 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeZamExWrWMr_gIB5b:-KFev9Ndl2iwmz045ais:952814224) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L405)):*
Yeah, but there I have not idea what's a file and what's a directory.

---

*[storage/storage.py, line 408 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFe_h8baB826SqmVlhe:-KFev3xNB8pjTxcgUQdq:-1213985015) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L408)):*
Good catch. Fixed.

---

*[tests/test_storage.py, line 15 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFQkVk0CRpp6ZcjM_rd:-KFexhcl9_poAAhpD_lj:-499146009) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/tests/test_storage.py#L15)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Comment by aztlan2k** [comment]
Reviewed 4 of 4 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/storage.py, line 405 \[r8\]](https://reviewable.io:443/reviews/ustudio/storage/28#-KFeZamExWrWMr_gIB5b:-KFezGeUPopUaM73uGOH:-294803015) ([raw file](https://github.com/ustudio/storage/blob/9fc05bf113fc61649544d1735df2b457c828180e/storage/storage.py#L405)):*
i think it returns the output in the same format as a 'LIST'.   `dir(callback) == retrlines('LIST', callback)` and `nlist(callback) == retrlines('NLST', callback)`.     *i think*

but it doesn't matter... it's the same thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/28)*

**Pull request merged**
