### PR TITLE
License update

### PR DESCRIPTION
**Pull request by cschmit**
[Review on Reviewable](https://reviewable.io/reviews/ustudio/storage/27)

### CODE REVIEW

**Comment by aztlan2k** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[LICENSE, line 11 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/27#-KCzr0WYZdeG2XXmih1q:-KCzr0WYZdeG2XXmih1r:-762764089) ([raw file](https://github.com/ustudio/storage/blob/16b733eebf10d405442385f7fd812bd33707243f/LICENSE#L11)):*
there's some *extra* chars at the end of the line here... not sure what they are or if they should be there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/27)*

**Comment by aztlan2k** [comment]
just that single comment about the strange chars at the end of the license file.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/27#-:-KCzrBGt7BsS9NFgM_7j:-1176180604)*

**Comment by cschmit** [comment]
Ready for re-review.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/27#-:-KCzwb4EImw-SZgKGPQ4:-1505720331)*

**Comment by aztlan2k** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ustudio/storage/27)*

**Pull request merged**
