### PR TITLE
publish to PyPI from CircleCI

### PR DESCRIPTION
**Pull request by fearphage**
@ustudio/dev :eyes:

---
This change is [Reviewable](https://reviewable.io/reviews/ustudio/storage/29)

### CODE REVIEW

**Comment by spiralman** [comment]
*[publish_to_pypi.sh, line 11 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/29#-KFowjMbAkhu3q64g0OG:-KFowjMbAkhu3q64g0OH:-1113367692) ([raw file](https://github.com/ustudio/storage/blob/6dbf84ebf5f920d6b5b399dd54c06856d5b8d489/publish_to_pypi.sh#L11)):*
Do you really need this if you're doing `set -e`? Is it just for a nicer error message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/29)*

**Comment by spiralman** [comment]
*[circle.yml, line 3 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/29#-KFowtBxhG4NOLKhNe_5:-KFowtBxhG4NOLKhNe_6:-1630283961) ([raw file](https://github.com/ustudio/storage/blob/6dbf84ebf5f920d6b5b399dd54c06856d5b8d489/circle.yml#L3)):*
It's somewhat irrelevant, but i kindof prefer `vX.Y.Z` (also, that's how Josh did the naming for uStudioTech in his PR to separate it out)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/29)*

**Comment by spiralman** [comment]
*[circle.yml, line 4 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/29#-KFoxBeeInaqWga6HI9o:-KFoxBefN6aKfWKqlSiQ:-669226839) ([raw file](https://github.com/ustudio/storage/blob/6dbf84ebf5f920d6b5b399dd54c06856d5b8d489/circle.yml#L4)):*
This should actually be `ustudio` (it means, which owner of the GitHub repo to check tags on)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/29)*

**Comment by spiralman** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/29)*

**Comment by fearphage** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[circle.yml, line 3 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/29#-KFowtBxhG4NOLKhNe_5:-KFoxoBS1h48QMyh23Fl:-499146009) ([raw file](https://github.com/ustudio/storage/blob/6dbf84ebf5f920d6b5b399dd54c06856d5b8d489/circle.yml#L3)):*
Done.

---

*[circle.yml, line 4 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/29#-KFoxBeeInaqWga6HI9o:-KFoxnfMaKKWDwl_8ZDf:-499146009) ([raw file](https://github.com/ustudio/storage/blob/6dbf84ebf5f920d6b5b399dd54c06856d5b8d489/circle.yml#L4)):*
Done.

---

*[publish_to_pypi.sh, line 11 \[r1\]](https://reviewable.io:443/reviews/ustudio/storage/29#-KFowjMbAkhu3q64g0OG:-KFowrZS3KB7ipjMJ9gD:1567174979) ([raw file](https://github.com/ustudio/storage/blob/6dbf84ebf5f920d6b5b399dd54c06856d5b8d489/publish_to_pypi.sh#L11)):*
It's only for nicer error messages really. I was thinking grep-friendly messages here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/29)*

**Comment by spiralman** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/storage/29)*

**Pull request merged**
